baseURL:
languageCode: en-us
title: 0bug
buildDrafts: true
copyright: 0bug
titleCaseStyle: none

params:
  description: Learn Hack Fail Repeat
  mode: toggle
  social:
    - name: GitHub
      icon: github
      url: https://github.com/0bugTeam
    - name: CTFtime
      icon: flag
      url: https://ctftime.org/team/238436
    - name: RSS
      icon: rss
      url:
  members:
    - name: 1byteBoy
      link: https://github.com/1byteBoy
      picture: https://avatars.githubusercontent.com/1byteboy
      tags: [ 'null']
      description:
        - 11111111 66 111 121
        - /proc/kcore
    - name: zacian
      link: https://owasp.org/www-project-top-ten/
      picture: https://cdn.discordapp.com/avatars/730361554889080862/9694ee5b59069a4ee68c1f434eb3d020?size=1024
      tags: ['web', 'pwn', 'crypto']
      description:
        - A dedicated Bug Bounty Hunter
        - Web Security Wizard
    - name: syr1ne
      link: https://github.com/syr1ne
      picture: https://avatars.githubusercontent.com/u/167830358?v=4
      tags: ['web', 'misc', 'osint']
      description:
        - Professional Distro Hopper
        - philosopher
    - name: octodi
      link: 
      picture: https://cdn.discordapp.com/avatars/1082941763083321354/fa564dd1d6edd761ca04a3b29d981ccc?size=1024
      tags: ['web']
      description:
        - Cute Octopus that Hacks
    - name: zoozoo
      link: 
      picture: https://cdn.discordapp.com/avatars/854751340688048198/e94af50f3d25b9939dbc465b12f32efa?size=1024
      tags: ['pwn']
      description: 
        - zoozoo
    - name: coderebel_x
      link: 
      picture: https://cdn.discordapp.com/avatars/1272253304981684350/f4c31e53a1af1b10116bed66e8511a3e?size=1024
      tags: ['crypto']
      description:
        - Can solve crypto with pen and paper
    - name: Cha0s
      link: 
      picture: https://cdn.discordapp.com/avatars/782977640747106375/e6f5a4c0efd8d8d122486de9e7d6e85a?size=1024
      tags: ['reversing', 'osint']
      description:
        - Fear Him
  excludedSections:
    - about
    - events
  homeWriteupCnt: 10
  katex: true

menu:
  main:
    - name: Home
      url: /
      weight: 1
    - name: Events
      url: /events
      weight: 2
    - name: Tags
      url: /tags
      weight: 3
    - name: About
      url: /about
      weight: 4
